from __future__ import annotations

from typing import Any, Protocol

from musicvault.domain.models import Track


class SourceClient(Protocol):
    """网易云源端能力端口：用例只依赖此协议，不依赖具体 SDK 客户端。"""

    def login_with_cookie(self, cookie: str) -> Any: ...

    def get_playlist_info(self, playlist_id: int) -> dict[str, Any]: ...

    def get_playlist_tracks(self, playlist_id: int) -> list[Track]: ...

    def get_tracks_detail(self, track_ids: list[int]) -> dict[int, Track]: ...

    def get_track_detail(self, track_id: int) -> Track | None: ...

    def get_tracks_download_urls(self, track_ids: list[int]) -> dict[int, str | None]: ...

    def get_album_info(self, album_id: int) -> dict[str, Any]: ...

    def get_track_lyrics(self, track_id: int) -> dict[str, str]: ...


class InteractiveLoginApi(Protocol):
    """CLI 交互登录所需的最小源端接口（登录交互专用，区别于用例级 SourceClient）。

    由 composition root 创建 NeteaseClient 后注入 CLI；返回类型放宽为 Any，
    登录结果的领域对象由 presentation 层按属性读取。
    """

    def get_qrcode_unikey(self) -> str: ...

    def get_qrcode_url(self, unikey: str) -> str: ...

    def check_qrcode(self, unikey: str) -> int: ...

    def get_login_status(self) -> Any: ...

    def login_via_phone(self, phone: str, password: str = ..., captcha: str = ..., ctcode: int = ...) -> Any: ...

    def send_sms_code(self, phone: str, ctcode: int = ...) -> bool: ...

    def extract_cookie(self) -> str: ...

    def login_with_cookie(self, cookie: str) -> Any: ...

    def list_user_playlists(self, user_id: int) -> list[dict[str, Any]]: ...
