from __future__ import annotations

from typing import Any, Protocol

from musicvault.domain.models import Track


class SourceClient(Protocol):
    """网易云源端能力端口：用例只依赖此协议，不依赖具体 SDK 客户端。"""

    def login_with_cookie(self, cookie: str) -> Any: ...

    def get_playlist_info(self, playlist_id: int) -> dict[str, Any]: ...

    def get_playlist_tracks(self, playlist_id: int) -> list[Track]: ...

    def get_tracks_detail(self, track_ids: list[int]) -> dict[int, Track]: ...

    def get_track_detail(self, track_id: int) -> Track | None: ...

    def get_tracks_download_urls(self, track_ids: list[int]) -> dict[int, str | None]: ...

    def get_album_info(self, album_id: int) -> dict[str, Any]: ...

    def get_track_lyrics(self, track_id: int) -> dict[str, str]: ...
