"""源侧状态端口：曲目/歌单/管理标记/媒体资产/歌词原稿的读写能力。"""

from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from musicvault.domain.models import MediaAsset, Playlist, SourceSnapshot, Track


class SourceStateRepository(Protocol):
    """源侧状态的最小公开查询与写入能力。"""

    def create_snapshot(self) -> SourceSnapshot: ...

    def get_track(self, track_id: int) -> Track | None: ...

    def upsert_track(self, track: Track, *, connection: Any = None) -> None: ...

    def remove_track(self, track_id: int, *, connection: Any = None) -> None: ...

    def upsert_playlist(self, playlist: Playlist, *, connection: Any = None) -> None: ...

    def get_playlist(self, playlist_id: int) -> Playlist | None: ...

    def list_playlists(self) -> list[Playlist]: ...

    def remove_playlist(self, playlist_id: int, *, connection: Any = None) -> None: ...

    def add_managed_track(self, track_id: int, *, connection: Any = None) -> None: ...

    def has_managed_track(self, track_id: int) -> bool: ...

    def list_managed_tracks(self) -> list[int]: ...

    def remove_managed_track(self, track_id: int) -> None: ...

    def upsert_media_asset(self, asset: MediaAsset, *, connection: Any = None) -> None: ...

    def list_media_assets(self, track_id: int | None = None) -> list[MediaAsset]: ...

    def save_lyrics(self, track_id: int, payload: str, fetched_at: float, *, connection: Any = None) -> None: ...

    def get_lyrics(self, track_id: int) -> str | None: ...

    def transaction(self) -> AbstractContextManager[Any]: ...
