from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol

from musicvault.domain.models import Track
from musicvault.domain.models import MediaAsset, Playlist, SourceSnapshot


class StateRepository(Protocol):
    """结构化状态的最小公开查询与写入能力。"""

    def create_snapshot(self) -> SourceSnapshot: ...

    def upsert_track(self, track: Track, *, connection: Any = None) -> None: ...

    def upsert_playlist(self, playlist: Playlist, *, connection: Any = None) -> None: ...

    def upsert_media_asset(self, asset: MediaAsset, *, connection: Any = None) -> None: ...

    def add_managed_song(self, track_id: int, *, connection: Any = None) -> None: ...

    def remove_track(self, track_id: int, *, connection: Any = None) -> None: ...

    def remove_playlist(self, playlist_id: int, *, connection: Any = None) -> None: ...

    def record_processed(self, track_id: int, preset_hash: str, updated_at: float) -> None: ...

    def is_processed(self, track_id: int, required_specs: set[str]) -> bool: ...

    def add_pending_file(self, path: str, track_id: int) -> None: ...

    def find_track_id_by_path(self, path: str) -> int | None: ...

    def transaction(self) -> AbstractContextManager[Any]: ...
